// Turns the original Illustrator logo into src/brand/logoPaths.js.
//
//   pdftocairo -svg -f 1 -l 1 assets/brand/source/Logo_WERTIS.pdf assets/brand/source/Logo_WERTIS-p1.svg
//   npm run import-logo
//
// Page 1 of the PDF is the colour logo. The renderer recolours it, so only the shapes and
// their roles are kept: "dark" (gear + WERTIS), "arc" (the orange arc in the gear) and
// "line" (SKLEP Z CZĘŚCIAMI). The other pages (green, white, black) are the same shapes in
// other colours, which the colour presets reproduce.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { readPaths, unionBox, mapPath } from './lib/svgPaths.js';

const root = fileURLToPath(new URL('..', import.meta.url));

export function importLogo(svg) {
  // Illustrator also wrote clipped duplicates of the gear and arc; the plain paths are enough.
  const paths = readPaths(svg).filter((p) => !p.clipped && p.fill);
  const isOrange = (p) => /rgb\(100%, 5\d/.test(p.fill);
  const dark = paths.filter((p) => !isOrange(p));
  const orange = paths.filter(isOrange);
  const wordTop = Math.min(...dark.filter((p) => p.rule === 'nonzero').map((p) => p.box[1]));
  const parts = {
    mark: { dark: dark.filter((p) => p.box[3] < wordTop), arc: orange.filter((p) => p.box[3] < wordTop) },
    word: { dark: dark.filter((p) => p.box[1] >= wordTop) },
    line: { line: orange.filter((p) => p.box[1] >= wordTop) },
  };
  const all = unionBox(paths.map((p) => p.box));
  const [ox, oy] = all;
  const out = {};
  for (const [name, roles] of Object.entries(parts)) {
    const list = Object.values(roles).flat();
    const b = unionBox(list.map((p) => p.box));
    out[name] = { box: [b[0] - ox, b[1] - oy, b[2] - b[0], b[3] - b[1]].map((v) => Math.round(v * 100) / 100) };
    for (const [role, ps] of Object.entries(roles)) {
      out[name][role] = { rule: ps.some((p) => p.rule === 'evenodd') ? 'evenodd' : 'nonzero', d: ps.map((p) => mapPath(p.d, 1, -ox, -oy)).join(' ') };
    }
  }
  return { size: [all[2] - ox, all[3] - oy].map((v) => Math.round(v * 100) / 100), parts: out };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const input = process.argv[2] ?? `${root}assets/brand/source/Logo_WERTIS-p1.svg`;
  const logo = importLogo(readFileSync(input, 'utf8'));
  writeFileSync(`${root}src/brand/logoPaths.js`, `// Generated by scripts/import-logo.js from assets/brand/source/Logo_WERTIS.pdf. Do not edit by hand.
// Units are the PDF's points. Each part has a box [x, y, w, h] and its colour roles:
// dark (gear + WERTIS), arc (the arc inside the gear), line (SKLEP Z CZĘŚCIAMI).
export const LOGO = ${JSON.stringify(logo, null, 1)};
`);
  const p = logo.parts;
  writeFileSync(`${root}assets/brand/wertis-logo.svg`, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${logo.size.join(' ')}">
<path fill="#303030" fill-rule="${p.mark.dark.rule}" d="${p.mark.dark.d}"/>
<path fill="#ff9100" fill-rule="${p.mark.arc.rule}" d="${p.mark.arc.d}"/>
<path fill="#303030" fill-rule="${p.word.dark.rule}" d="${p.word.dark.d}"/>
<path fill="#ff9100" fill-rule="${p.line.line.rule}" d="${p.line.line.d}"/>
</svg>
`);
  console.log('logo', logo.size, Object.fromEntries(Object.entries(p).map(([k, v]) => [k, v.box])));
}
