// Turns the parts icons of the WERTIS foil-mailer artwork (Foliopak.pdf) into
// src/brand/patternIcons.js, the shapes the background pattern scatters.
//
//   pdftocairo -svg Foliopak.pdf foliopak.svg
//   npm run import-icons -- foliopak.svg
//
// The artwork has every icon several times in grey (front) and orange (back). The grey ones
// are clustered into icons, and PICK names the distinct ones by their cluster index.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { readPaths, cluster, mapPath } from './lib/svgPaths.js';

const root = fileURLToPath(new URL('..', import.meta.url));
const GREY = 'rgb(65.492249%, 64.863586%, 65.019226%)';

// Cluster index → icon. The skipped clusters are repeats, or icons the artwork cut at its edge.
export const PICK = [
  [0, 'coil', 'Ignition coil'],
  [1, 'blade', 'Trimmer blade'],
  [2, 'coilLead', 'Ignition coil with lead'],
  [3, 'starter', 'Recoil starter'],
  [4, 'spring', 'Spring'],
  [5, 'starterPlate', 'Starter plate'],
  [6, 'sparkPlug', 'Spark plug'],
  [7, 'airFilter', 'Air filter'],
  [8, 'springLong', 'Long spring'],
  [9, 'cylinder', 'Cylinder'],
  [11, 'crankshaft', 'Crankshaft'],
  [13, 'conRod', 'Crank and connecting rod'],
  [16, 'fuelFilter', 'Fuel filter'],
  [17, 'airFilterTall', 'Air filter (tall)'],
  [21, 'carburettor', 'Carburettor'],
];

// Each icon is fitted into a 100-unit box centred on (0, 0), so the pattern can rotate and
// scale it about its middle.
export function importIcons(svg) {
  const groups = cluster(readPaths(svg, { includeDefs: true }).filter((p) => p.fill === GREY));
  return PICK.map(([index, id, label]) => {
    const g = groups[index];
    const [x0, y0, x1, y1] = g.box;
    const s = 100 / Math.max(x1 - x0, y1 - y0);
    const cx = (x0 + x1) / 2, cy = (y0 + y1) / 2;
    const byRule = { nonzero: [], evenodd: [] };
    for (const p of g.paths) byRule[p.rule].push(mapPath(p.d, s, -cx * s, -cy * s, 2));
    return {
      id, label,
      w: Math.round((x1 - x0) * s * 10) / 10, h: Math.round((y1 - y0) * s * 10) / 10,
      paths: Object.entries(byRule).filter(([, ds]) => ds.length).map(([rule, ds]) => ({ rule, d: ds.join(' ') })),
    };
  });
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (!process.argv[2]) throw new Error('usage: npm run import-icons -- <foliopak.svg>');
  const icons = importIcons(readFileSync(process.argv[2], 'utf8'));
  writeFileSync(`${root}src/brand/patternIcons.js`, `// Generated by scripts/import-icons.js from the WERTIS foil-mailer artwork (Foliopak.pdf).
// Do not edit by hand. Each icon fits a 100-unit box centred on (0, 0); w and h are its size.
export const PATTERN_ICONS = ${JSON.stringify(icons, null, 1)};
`);
  console.log(icons.map((i) => `${i.id} ${i.w}×${i.h}`).join(', '));
}
